MERGE INTO T_CODIGOS_POSTALES t
USING CODIGOS_POSTALES c
ON c.id = t.id
WHEN NOT MATCHED THEN
INSERT (t.ID, t.ID_PROVINCIA, t.LOCALIDAD, t.CODIGO_POSTAL) 
    values (c.ID, c.IDPROVINCIA, c.LOCALIDAD, c.CODIGO_POSTAL);