--Computed Field
ALTER TABLE CONSULTAS_APROBADAS ADD TOTALCOSTO COMPUTED BY (CAST((costo - (costo * (descuento/100))) as D_DINERO));
ALTER TABLE DATOS_NACIMIENTO ADD MC COMPUTED BY (CAST(pesoNacimientoKG/(altura*altura) as d_Medida));

--Foreing Key
ALTER TABLE ANALISIS ADD CONSTRAINT ANALISIS_FK
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES (ID);
ALTER TABLE ANTECEDENTES ADD CONSTRAINT ANTECEDENTES_FK
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES (ID);
ALTER TABLE ASEGURADOS ADD CONSTRAINT FK_ASEGURADOS_0
  FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS (ID);
ALTER TABLE ASEGURADOS ADD CONSTRAINT FK_ASEGURADOS_1
  FOREIGN KEY (ID_ARS) REFERENCES ARS (ID);
ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTES_0
  FOREIGN KEY (ID) REFERENCES PERSONAS (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE CODIGOS_POSTALES ADD CONSTRAINT LOCALIDADES_POSTALES_FK
  FOREIGN KEY (IDPROVINCIA) REFERENCES PROVINCIAS (ID);
CREATE INDEX CODIGO_POSTAL_IDX ON CODIGOS_POSTALES (CODIGO_POSTAL);
ALTER TABLE CONSULTAS ADD CONSTRAINT CONSULTAS_FK
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES (ID);
ALTER TABLE CONSULTAS ADD CONSTRAINT CONSULTAS_FK_1
  FOREIGN KEY (ID_CONTROL_CONSULTA) REFERENCES CONTROL_CONSULTA (ID);
ALTER TABLE CONSULTAS ADD CONSTRAINT CONSULTAS_FK_2
  FOREIGN KEY (ID_MOTIVO_CONSULTA) REFERENCES MOTIVO_CONSULTA (ID);
ALTER TABLE CONSULTAS_APROBADAS ADD CONSTRAINT CONSULTAS_APROBADAS_FK
  FOREIGN KEY (ID) REFERENCES CONSULTAS (ID);
ALTER TABLE CONTACTOS_EMAIL ADD CONSTRAINT FK_CONTACTOS_EMAIL_0
  FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS (ID);
ALTER TABLE CONTACTOS_TEL ADD CONSTRAINT FK_CONTACTOS_TEL_0
  FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS (ID);
ALTER TABLE DATOS_NACIMIENTO ADD CONSTRAINT FK_DATOSNACIMIENTO_1
  FOREIGN KEY (ID) REFERENCES PERSONAS (ID);
ALTER TABLE DEUDAS ADD CONSTRAINT DEUDAS_FK_1
  FOREIGN KEY (ID_FACTURA) REFERENCES FACTURAS (ID);
ALTER TABLE DEUDAS ADD CONSTRAINT FK_DEUDAS_0
  FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS (ID);
ALTER TABLE DIRECCIONES ADD CONSTRAINT FK_DIRECCIONES_0
  FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS (ID);
ALTER TABLE DIRECCIONES ADD CONSTRAINT FK_DIRECCIONES_1
  FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIAS (ID);
ALTER TABLE DIRECCIONES ADD CONSTRAINT FK_DIRECCIONES_2
  FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIOS (ID);
ALTER TABLE DIRECCIONES ADD CONSTRAINT FK_DIRECCIONES_3
  FOREIGN KEY (ID_DISTRITO_MUNICIPAL) REFERENCES DISTRITOS_MUNICIPALES (ID);
ALTER TABLE DIRECCIONES ADD CONSTRAINT FK_DIRECCIONES_4
  FOREIGN KEY (ID_CODIGO_POSTAL) REFERENCES CODIGOS_POSTALES (ID);
ALTER TABLE DISTRITOS_MUNICIPALES ADD CONSTRAINT IDMUNICIPIO_IDX
  FOREIGN KEY (IDMUNICIPIO) REFERENCES MUNICIPIOS (ID);
ALTER TABLE D_DEUDAS_PAGAS ADD CONSTRAINT D_DEUDAS_PAGAS_FK
  FOREIGN KEY (ID_DEUDAS) REFERENCES DEUDAS (ID);
ALTER TABLE D_FACTURAS ADD CONSTRAINT FK_D_FACTURAS_0
  FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID);
ALTER TABLE D_FACTURAS ADD CONSTRAINT FK_D_FACTURAS_1
  FOREIGN KEY (ID_FACTURA) REFERENCES FACTURAS (ID);
ALTER TABLE D_GUIA_VIGILANCIA_DESARROLLO ADD CONSTRAINT FK_DETALLE_GUIA_VIG_1
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES (ID);
ALTER TABLE D_GUIA_VIGILANCIA_DESARROLLO ADD CONSTRAINT FK_DETALLE_GUIA_VIG_2
  FOREIGN KEY (ID_GVD) REFERENCES GUIA_VIGILANCIA_DESARROLLO (ID);
ALTER TABLE D_MOTIVO_CONSULTA ADD CONSTRAINT FK_D_MOTIVO_CONSULTA_1
  FOREIGN KEY (IDCONSULTA) REFERENCES CONSULTAS (ID) ON DELETE CASCADE;
ALTER TABLE D_MOTIVO_CONSULTA ADD CONSTRAINT FK_D_MOTIVO_CONSULTA_2
  FOREIGN KEY (IDMCONSULTA) REFERENCES MOTIVO_CONSULTA (ID) ON DELETE CASCADE;
ALTER TABLE D_RECETAS ADD CONSTRAINT FK_DETALLERECETAS_2
  FOREIGN KEY (ID_RECETA) REFERENCES RECETAS (ID);
ALTER TABLE D_RECETAS ADD CONSTRAINT FK_D_RECETAS_1
  FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTOS (ID);
ALTER TABLE ENTRADA_PRODUCTOS ADD CONSTRAINT FK_ENTRADA_PRODUCTOS_0
  FOREIGN KEY (IDPROVEDOR) REFERENCES PROVEEDORES (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE ENTRADA_PRODUCTOS ADD CONSTRAINT FK_ENTRADA_PRODUCTOS_1
  FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE ESTUDIANTE ADD CONSTRAINT FK_ESTUDIANTE_0
  FOREIGN KEY (ID_TUTOR) REFERENCES PERSONAS (ID);
ALTER TABLE ESTUDIANTE ADD CONSTRAINT FK_ESTUDIANTE_1
  FOREIGN KEY (ID) REFERENCES PERSONAS (ID);
ALTER TABLE ESTUDIANTE ADD CONSTRAINT FK_MADRE
  FOREIGN KEY (ID_MADRE) REFERENCES PERSONAS (ID);
ALTER TABLE ESTUDIANTE ADD CONSTRAINT FK_PADRE
  FOREIGN KEY (ID_PADRE) REFERENCES PERSONAS (ID);
ALTER TABLE FACTURAS ADD CONSTRAINT FACTURAS_FK
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID);
ALTER TABLE FACTURAS ADD CONSTRAINT FK_FACTURA_2
  FOREIGN KEY (IDTURNO) REFERENCES TURNOS (ID);
ALTER TABLE GENERALES ADD CONSTRAINT FK_GENERALES_0
  FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GENERALES ADD CONSTRAINT FK_GENERALES_1
  FOREIGN KEY (ID_TIPO_SANGRE) REFERENCES TIPOS_SANGRE (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE HUELLAS ADD CONSTRAINT HUELLAS_FK
  FOREIGN KEY (ID) REFERENCES PERSONAS (ID);
ALTER TABLE INSCRIPCIONES ADD CONSTRAINT FK_ESTUDIANTE
  FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE (ID);
ALTER TABLE INSCRIPCIONES ADD CONSTRAINT FK_PADRE_TUTOR
  FOREIGN KEY (ID_PADRE_TUTOR) REFERENCES PADRES (ID);
ALTER TABLE INSCRIPCIONES ADD CONSTRAINT FK_TANDAS
  FOREIGN KEY (ID_TANDA) REFERENCES TANDAS (ID);
ALTER TABLE MEDICAMENTOS ADD CONSTRAINT FK_MEDICAMENTOS_1
  FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES (ID);
ALTER TABLE MENSAJES ADD CONSTRAINT MENSAJES_FK
  FOREIGN KEY (ID_PACIENTE) REFERENCES PERSONAS (ID);
ALTER TABLE METRICAS ADD CONSTRAINT FK_METRICAS_1
  FOREIGN KEY (IDCONSULTA) REFERENCES CONSULTAS (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE MUNICIPIOS ADD CONSTRAINT IDPROVINCIA_IDX
  FOREIGN KEY (IDPROVINCIA) REFERENCES PROVINCIAS (ID);
ALTER TABLE PACIENTES ADD CONSTRAINT FK_PACIENTES_0
  FOREIGN KEY (ID) REFERENCES PERSONAS (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE PACIENTES ADD CONSTRAINT PACIENTES_FK
  FOREIGN KEY (ID_MADRE) REFERENCES PADRES (ID);
ALTER TABLE PACIENTES ADD CONSTRAINT PACIENTES_FK_1
  FOREIGN KEY (ID_PADRE) REFERENCES PADRES (ID);
ALTER TABLE PADRES ADD CONSTRAINT FK_PADRES_0
  FOREIGN KEY (ID) REFERENCES PERSONAS (ID);
ALTER TABLE PRODUCTOS ADD CONSTRAINT FK_PRODUCTOS_0
  FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIAS (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE PROVEEDORES ADD CONSTRAINT FK_PROVEEDORES_0
  FOREIGN KEY (ID) REFERENCES PERSONAS (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
CREATE UNIQUE INDEX RECCOUNT_IDX1 ON RECCOUNT (TABLA);
ALTER TABLE RECETAS ADD CONSTRAINT FK_RECETAS_1
  FOREIGN KEY (IDCONSULTA) REFERENCES CONSULTAS (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE SINTOMAS ADD CONSTRAINT SINTOMAS_FK
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES (ID);

CREATE INDEX IDX_PERSONAS1 ON PERSONAS (PNOMBRE);
CREATE INDEX IDX_PERSONAS2 ON PERSONAS (SNOMBRE);
CREATE INDEX IDX_PERSONAS3 ON PERSONAS (APELLIDOS);
CREATE INDEX IDX_PERSONAS4 ON PERSONAS (FECHA_NACIMIENTO);
CREATE INDEX IDX_PERSONAS5 ON PERSONAS (FECHA_INGRESO);

GRANT RRR_SECRETARIA TO JHIRONSEL WITH ADMIN OPTION;


GRANT EXECUTE
 ON PROCEDURE SP_RECCOUNT_ESTADO TO  "PUBLIC";

GRANT REFERENCES(ID), SELECT
 ON GET_CLIENTES_SB TO ROLE RRR_SECRETARIA;

GRANT REFERENCES(ID,ID_CODIGO_POSTAL,ID_DISTRITO_MUNICIPAL,ID_MUNICIPIO,ID_PROVINCIA,ID_PERSONA), SELECT
 ON GET_DIRECCION_BY_ID TO ROLE RRR_SECRETARIA;

GRANT SELECT
 ON GET_PRIVILEGIOS TO  "PUBLIC";

GRANT SELECT
 ON GET_ROL TO  "PUBLIC";



GRANT SELECT
 ON GET_USER_ROLES TO  "PUBLIC";

GRANT SELECT
 ON V_ANALISIS TO ROLE RRR_DOCTOR;

GRANT SELECT
 ON V_ANTECEDENTES TO ROLE RRR_DOCTOR;


GRANT SELECT
 ON V_ARS TO ROLE RRR_DOCTOR;



GRANT SELECT
 ON V_CLIENTES TO ROLE RRR_CAJERO;

GRANT REFERENCES(ID,ID_PERSONA), SELECT
 ON V_CONTACTS_EMAIL TO ROLE RRR_SECRETARIA;

GRANT SELECT
 ON V_CONTACTS_TEL TO ROLE RRR_SECRETARIA;

GRANT SELECT
 ON V_DIRECCIONES TO ROLE RRR_SECRETARIA;


GRANT SELECT
 ON V_D_GUIA_VIGILANCIA_DESARROLLO TO ROLE RRR_DOCTOR;


GRANT SELECT
 ON V_E_S_SYS TO  "PUBLIC";

GRANT INSERT
 ON V_FACTURAS TO ROLE RRR_CAJERO;

GRANT SELECT
 ON V_FCH_LC TO  "PUBLIC";

GRANT SELECT
 ON V_GENERALES TO ROLE RRR_SECRETARIA;

GRANT SELECT
 ON V_MUNICIPIOS TO  "PUBLIC";

GRANT SELECT
 ON V_PERSONAS TO ROLE RRR_CAJERO;

GRANT SELECT
 ON V_PERSONAS TO ROLE RRR_SECRETARIA;

GRANT SELECT
 ON V_PRODUCTOS TO ROLE RRR_CAJERO;

GRANT SELECT
 ON V_PRODUCTOS TO ROLE RRR_VENDEDOR;

GRANT SELECT
 ON V_PROVINCIAS TO  "PUBLIC";

GRANT SELECT
 ON V_TIME_LIC TO  "PUBLIC";

GRANT SELECT
 ON V_TIPOS_SANGRE TO  "PUBLIC";
