INSERT INTO ARS (DESCRIPCION, COVERCONSULTAPORC) VALUES ('Ingrese tipo de seguro', 0.00);
INSERT INTO ARS (DESCRIPCION, COVERCONSULTAPORC) VALUES ('Senasa', 60.00);
INSERT INTO ARS (DESCRIPCION, COVERCONSULTAPORC) VALUES ('Palic', 63.00);
INSERT INTO ARS (DESCRIPCION, COVERCONSULTAPORC) VALUES ('Humano', 45.50);
INSERT INTO ARS (DESCRIPCION, COVERCONSULTAPORC) VALUES ('Semma', 70.00);
INSERT INTO ARS (DESCRIPCION, COVERCONSULTAPORC) VALUES ('Prueba', 26.80);
