INSERT INTO CATEGORIAS (ID, DESCRIPCION, ESTADO) VALUES ('1', 'Embutidos', 'true');
INSERT INTO CATEGORIAS (ID, DESCRIPCION, ESTADO) VALUES ('2', 'Lateos', 'true');
INSERT INTO CATEGORIAS (ID, DESCRIPCION, ESTADO) VALUES ('3', 'Cervezas', 'true');
INSERT INTO CATEGORIAS (ID, DESCRIPCION, ESTADO) VALUES ('4', 'Jabones', 'true');
