INSERT INTO CATEGORIAS (DESCRIPCION, ESTADO) VALUES ('Embutidos', true);
INSERT INTO CATEGORIAS (DESCRIPCION, ESTADO) VALUES ('Lateos', true);
INSERT INTO CATEGORIAS (DESCRIPCION, ESTADO) VALUES ('Cervezas', true);
INSERT INTO CATEGORIAS (DESCRIPCION, ESTADO) VALUES ('Jabones', true);
