INSERT INTO PRODUCTOS (ID, IDCATEGORIA, CODIGO, DESCRIPCION, IMAGEN_TEXTO, NOTA, 
FECHA_CREACION, ESTADO, IDUSUARIO, ROL) VALUES ('1', '1', '0000', 'Jamon Induveca', 
NULL, 'N/A', '13.08.2022', 'true', 'SYSDBA', 'NONE                           ');
