INSERT INTO ARS (ID, DESCRIPCION, COVERCONSULTAPORC, ESTADO) VALUES ('0', 'Ingrese tipo de seguro', '0.00', 'true');
INSERT INTO ARS (ID, DESCRIPCION, COVERCONSULTAPORC, ESTADO) VALUES ('1', 'Senasa', '60.00', 'true');
INSERT INTO ARS (ID, DESCRIPCION, COVERCONSULTAPORC, ESTADO) VALUES ('2', 'Palic', '63.00', 'true');
INSERT INTO ARS (ID, DESCRIPCION, COVERCONSULTAPORC, ESTADO) VALUES ('3', 'Humano', '45.50', 'true');
INSERT INTO ARS (ID, DESCRIPCION, COVERCONSULTAPORC, ESTADO) VALUES ('4', 'Semma', '70.00', 'true');
