EXECUTE PROCEDURE SP_INSERT_ARS ('Ingrese tipo de seguro', 0.00, true);
EXECUTE PROCEDURE SP_INSERT_ARS ('Senasa', 60.00, true);
EXECUTE PROCEDURE SP_INSERT_ARS ('Palic', 63.00, true);
EXECUTE PROCEDURE SP_INSERT_ARS ('Humano', 45.50, true);
EXECUTE PROCEDURE SP_INSERT_ARS ('Semma', 70.00, true);
