/**
 * Author:  jhironsel
 * Created: 1 oct. 2022
 */

UPDATE
    RDB$PROCEDURES
SET
    RDB$PROCEDURE_SOURCE = NULL
WHERE
    RDB$SYSTEM_FLAG IS NULL OR RDB$SYSTEM_FLAG = 0;
 
UPDATE
    RDB$TRIGGERS
SET
    RDB$TRIGGER_SOURCE = NULL
WHERE
    RDB$SYSTEM_FLAG IS NULL OR RDB$SYSTEM_FLAG = 0;
 
UPDATE
    RDB$RELATIONS
SET
    RDB$VIEW_SOURCE = NULL
WHERE
    (RDB$SYSTEM_FLAG IS NULL OR RDB$SYSTEM_FLAG = 0) AND RDB$VIEW_BLR IS NOT NULL;
