CREATE DOMAIN D_APELLIDOS
 AS VARCHAR(40)
 CHECK (value similar to '[[:ALPHA:]-'' .]*' escape '@');

CREATE DOMAIN D_BLOB_TEXTO
 AS text;

CREATE DOMAIN D_BOOLEAN_F
 AS BOOLEAN
 DEFAULT FALSE
 NOT NULL;
 
CREATE DOMAIN D_BOOLEAN_T
 AS BOOLEAN
 DEFAULT TRUE
;

CREATE DOMAIN D_CEDULA
 AS CHAR(13)
 CHECK (value similar to '[[:DIGIT:]]{3}[-][[:DIGIT:]]{7}[-][[:DIGIT:]]{1}');
 
CREATE DOMAIN D_CLAVE
 AS VARCHAR(30);

CREATE DOMAIN D_CODIGO
 AS VARCHAR(20);
 
CREATE DOMAIN D_CODIGO_PAI
 AS CHAR(7);
 
CREATE DOMAIN D_CORREO
 AS VARCHAR(100)
 CHECK (trim(VALUE) ~* '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$');
	 
CREATE DOMAIN D_DEDO
 AS CHAR(2)
 DEFAULT 'IN'
 NOT NULL
 CHECK (value in('PU', 'IN', 'MA', 'AN', 'ME'));
 
CREATE DOMAIN D_DESCUENTO
 AS NUMERIC(5,2)
 DEFAULT 0.00
 CHECK(VALUE >= 0 AND VALUE <= 100);
 
CREATE DOMAIN D_DIA
 AS CHAR(2)
 DEFAULT 'LU'
 CHECK (value in('LU', 'MA', 'MI', 'JU', 'VI', 'SA', 'DO'));
 
CREATE DOMAIN D_DINERO
 AS NUMERIC(18,2)
 DEFAULT 0.00;
 
CREATE DOMAIN D_EDAD
 AS SMALLINT
 DEFAULT 0
 NOT NULL
 CHECK (VALUE >= 0);
 
CREATE DOMAIN D_ESTADO_CIVIL
 AS CHAR(1)
 DEFAULT 'S'
 CHECK (VALUE IN ('S', 'C', 'D', 'V', 'U', 'X'));
 
CREATE DOMAIN D_ESTADO_C_I_P_A_N_T
 AS CHAR(1)
 DEFAULT 'i'
 CHECK (LOWER(VALUE) IN('c','i', 'p', 'a', 'n', 't'));
 
CREATE DOMAIN D_ESTADO_MENSAJES
 AS CHAR(1)
 DEFAULT 'N'
 NOT NULL
 CHECK (VALUE IN('N', 'L', 'R', 'B'));
 
CREATE DOMAIN D_FECHA
 AS DATE
 DEFAULT CURRENT_DATE;

CREATE DOMAIN D_FECHA_HORA
 AS TIMESTAMP
 DEFAULT CURRENT_TIMESTAMP;

CREATE DOMAIN D_HORA
 AS TIME
 DEFAULT CURRENT_TIME;

CREATE DOMAIN D_ID
 AS INTEGER
 DEFAULT NULL
 CHECK (value >= 0);

CREATE DOMAIN D_IDUSUARIO
 AS VARCHAR(31)
 DEFAULT current_user
 NOT NULL;
 
CREATE DOMAIN D_INSERT_DELETE
 AS CHAR(1)
 DEFAULT 'I'
 NOT NULL
 CHECK (UPPER(value) in('I', 'D'));
 
CREATE DOMAIN D_MEDIDA
 AS NUMERIC(18,2)
 DEFAULT 0.00;
 
CREATE DOMAIN D_NOMBRES
 AS VARCHAR(40)
 CHECK (value similar to '[[:ALPHA:]-'' .]*' escape '@');
 
CREATE DOMAIN D_PERSONA
 AS CHAR(1)
 DEFAULT 'F'
 CHECK (VALUE in ('F', 'J', 'X'));
 
CREATE DOMAIN D_PUNTO_CARDINALES
 AS VARCHAR(5)
 DEFAULT 'N/A'
 CHECK (VALUE IN('Norte', 'Este', 'Sur', 'Oeste', 'N/A'));
 
CREATE DOMAIN D_ROL
 AS CHAR(31)
 DEFAULT CURRENT_ROLE
 NOT NULL;
 
CREATE DOMAIN D_SANGRE_SIMBOLOS
 AS VARCHAR(3)
 DEFAULT 'N/A'
 CHECK (VALUE in('N/A','O-','O+', 'A-', 'A+', 'B-', 'B+', 'AB-', 'AB+'));
 
CREATE DOMAIN D_SEXO
 AS CHAR(1)
 DEFAULT 'M'
 CHECK (UPPER(value) = 'M' or UPPER(value) = 'F' or UPPER(value) = 'X');
 
CREATE DOMAIN D_TELEFONO
 AS CHAR(16)
 CHECK (value similar to '[+][1][(][[:digit:]]{3}[)][ ][[:digit:]]{3}[-][[:digit:]]{4}');
 
CREATE DOMAIN D_TURNO
 AS SMALLINT
 DEFAULT 0
 CHECK (value >= 1);

CREATE DOMAIN D_VARCHAR_15
 AS VARCHAR(15);
 
CREATE DOMAIN D_VARCHAR_25
 AS VARCHAR(25);
 
CREATE DOMAIN D_VARCHAR_255
 AS VARCHAR(255);
 
CREATE DOMAIN D_VARCHAR_45
 AS VARCHAR(45);
 
CREATE DOMAIN D_VARCHAR_70
 AS VARCHAR(70);