
ALTER TABLE ANALISIS ADD CONSTRAINT ANALISIS_FK
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES (ID);
ALTER TABLE ANTECEDENTES ADD CONSTRAINT ANTECEDENTES_FK
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES (ID);
ALTER TABLE ASEGURADOS ADD CONSTRAINT FK_ASEGURADOS_0
  FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS (ID);
ALTER TABLE ASEGURADOS ADD CONSTRAINT FK_ASEGURADOS_1
  FOREIGN KEY (ID_ARS) REFERENCES ARS (ID);
ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTES_0
  FOREIGN KEY (ID) REFERENCES PERSONAS (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE CODIGOS_POSTALES ADD CONSTRAINT LOCALIDADES_POSTALES_FK
  FOREIGN KEY (IDPROVINCIA) REFERENCES PROVINCIAS (ID);
CREATE INDEX CODIGO_POSTAL_IDX ON CODIGOS_POSTALES (CODIGO_POSTAL);
ALTER TABLE CONSULTAS ADD CONSTRAINT CONSULTAS_FK
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES (ID);
ALTER TABLE CONSULTAS ADD CONSTRAINT CONSULTAS_FK_1
  FOREIGN KEY (ID_CONTROL_CONSULTA) REFERENCES CONTROL_CONSULTA (ID);
ALTER TABLE CONSULTAS ADD CONSTRAINT CONSULTAS_FK_2
  FOREIGN KEY (ID_MOTIVO_CONSULTA) REFERENCES MOTIVO_CONSULTA (ID);
ALTER TABLE CONSULTAS_APROBADAS ADD TOTALCOSTO COMPUTED BY (CAST((costo - (costo * (descuento/100))) as D_DINERO));
ALTER TABLE CONSULTAS_APROBADAS ADD CONSTRAINT CONSULTAS_APROBADAS_FK
  FOREIGN KEY (ID) REFERENCES CONSULTAS (ID);
ALTER TABLE CONTACTOS_EMAIL ADD CONSTRAINT FK_CONTACTOS_EMAIL_0
  FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS (ID);
ALTER TABLE CONTACTOS_TEL ADD CONSTRAINT FK_CONTACTOS_TEL_0
  FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS (ID);
COMMENT ON COLUMN CONTROL_CONSULTA.USER_NAME IS 'Este campo es utilizando para guardar el usuario que va a tener consultas programadas cierto dias.';
COMMENT ON COLUMN CONTROL_CONSULTA.IDUSUARIO IS 'Este campo guarda el usuario que realizó el registro. ';
ALTER TABLE DATOS_NACIMIENTO ADD MC COMPUTED BY (CAST(pesoNacimientoKG/(altura*altura) as d_Medida));
ALTER TABLE DATOS_NACIMIENTO ADD CONSTRAINT FK_DATOSNACIMIENTO_1
  FOREIGN KEY (ID) REFERENCES PERSONAS (ID);
ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT FK_DETALLEFACTURA_0
  FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS (ID);
ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT FK_DETALLEFACTURA_1
  FOREIGN KEY (ID) REFERENCES FACTURAS (ID);
COMMENT ON COLUMN DEUDAS.ID IS 'Identificador de la deuda.';
COMMENT ON COLUMN DEUDAS.ID_PERSONA IS 'Identificador del Cliente';
COMMENT ON COLUMN DEUDAS.CONCEPTO IS 'Concepto por el cual se registra la deuda.';
COMMENT ON COLUMN DEUDAS.MONTO IS 'El monto de la deuda';
COMMENT ON COLUMN DEUDAS.FECHA IS 'La fecha de la deuda, se inserta SOLA';
COMMENT ON COLUMN DEUDAS.HORA IS 'La Hora tambien se Inserta SOLA';
COMMENT ON COLUMN DEUDAS.ESTADO IS 'Estado si es Deuda Inicial (i), Pagada (p), Abonada (a), Nulada (n).';
ALTER TABLE DEUDAS ADD CONSTRAINT DEUDAS_FK_1
  FOREIGN KEY (ID_FACTURA) REFERENCES FACTURAS (ID);
ALTER TABLE DEUDAS ADD CONSTRAINT FK_DEUDAS_0
  FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS (ID);
ALTER TABLE DIRECCIONES ADD CONSTRAINT FK_DIRECCIONES_0
  FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS (ID);
ALTER TABLE DIRECCIONES ADD CONSTRAINT FK_DIRECCIONES_1
  FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIAS (ID);
ALTER TABLE DIRECCIONES ADD CONSTRAINT FK_DIRECCIONES_2
  FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIOS (ID);
ALTER TABLE DIRECCIONES ADD CONSTRAINT FK_DIRECCIONES_3
  FOREIGN KEY (ID_DISTRITO_MUNICIPAL) REFERENCES DISTRITOS_MUNICIPALES (ID);
ALTER TABLE DIRECCIONES ADD CONSTRAINT FK_DIRECCIONES_4
  FOREIGN KEY (ID_CODIGO_POSTAL) REFERENCES CODIGOS_POSTALES (ID);
ALTER TABLE DISTRITOS_MUNICIPALES ADD CONSTRAINT IDMUNICIPIO_IDX
  FOREIGN KEY (IDMUNICIPIO) REFERENCES MUNICIPIOS (ID);
ALTER TABLE D_DEUDAS_PAGAS ADD CONSTRAINT D_DEUDAS_PAGAS_FK
  FOREIGN KEY (ID_DEUDAS) REFERENCES DEUDAS (ID);
COMMENT ON TABLE D_DEUDAS_PAGAS IS 'En esta tabla llevamos los pagos de los cliente a las deudas registrada en la tabla de Deudas.';
ALTER TABLE D_FACTURAS ADD CONSTRAINT FK_D_FACTURAS_0
  FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID);
ALTER TABLE D_FACTURAS ADD CONSTRAINT FK_D_FACTURAS_1
  FOREIGN KEY (ID_FACTURA) REFERENCES FACTURAS (ID);
ALTER TABLE D_GUIA_VIGILANCIA_DESARROLLO ADD CONSTRAINT FK_DETALLE_GUIA_VIG_1
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES (ID);
ALTER TABLE D_GUIA_VIGILANCIA_DESARROLLO ADD CONSTRAINT FK_DETALLE_GUIA_VIG_2
  FOREIGN KEY (ID_GVD) REFERENCES GUIA_VIGILANCIA_DESARROLLO (ID);
ALTER TABLE D_MOTIVO_CONSULTA ADD CONSTRAINT FK_D_MOTIVO_CONSULTA_1
  FOREIGN KEY (IDCONSULTA) REFERENCES CONSULTAS (ID) ON DELETE CASCADE;
ALTER TABLE D_MOTIVO_CONSULTA ADD CONSTRAINT FK_D_MOTIVO_CONSULTA_2
  FOREIGN KEY (IDMCONSULTA) REFERENCES MOTIVO_CONSULTA (ID) ON DELETE CASCADE;
ALTER TABLE D_RECETAS ADD CONSTRAINT FK_DETALLERECETAS_2
  FOREIGN KEY (ID_RECETA) REFERENCES RECETAS (ID);
ALTER TABLE D_RECETAS ADD CONSTRAINT FK_D_RECETAS_1
  FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTOS (ID);
ALTER TABLE ENTRADA_PRODUCTOS ADD CONSTRAINT FK_ENTRADA_PRODUCTOS_0
  FOREIGN KEY (IDPROVEDOR) REFERENCES PROVEEDORES (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE ENTRADA_PRODUCTOS ADD CONSTRAINT FK_ENTRADA_PRODUCTOS_1
  FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE ESTUDIANTE ADD CONSTRAINT FK_ESTUDIANTE_0
  FOREIGN KEY (ID_TUTOR) REFERENCES PERSONAS (ID);
ALTER TABLE ESTUDIANTE ADD CONSTRAINT FK_ESTUDIANTE_1
  FOREIGN KEY (ID) REFERENCES PERSONAS (ID);
ALTER TABLE ESTUDIANTE ADD CONSTRAINT FK_MADRE
  FOREIGN KEY (ID_MADRE) REFERENCES PERSONAS (ID);
ALTER TABLE ESTUDIANTE ADD CONSTRAINT FK_PADRE
  FOREIGN KEY (ID_PADRE) REFERENCES PERSONAS (ID);
COMMENT ON COLUMN FACTURAS.ID IS 'Identificador de la tabla facturas.';
COMMENT ON COLUMN FACTURAS.ID_CLIENTE IS 'Identificador del cliente';
COMMENT ON COLUMN FACTURAS.IDTURNO IS 'Turno que tiene asignado el cajero para realizar las operaciones de factura.';
COMMENT ON COLUMN FACTURAS.EFECTIVO IS 'Es el dinero que entrega el cliente al cajero.';
COMMENT ON COLUMN FACTURAS.CAMBIO IS 'Es el cambio que debe entregarle el cajero al cliente.';
COMMENT ON COLUMN FACTURAS.FECHA IS 'Fecha en la que se crea la factura.';
COMMENT ON COLUMN FACTURAS.HORA IS 'La hora en que se realiza la factura en el sistema.';
COMMENT ON COLUMN FACTURAS.ESTADO_FACTURA IS 'Este campo sirve para ver el estado de la factura que puede ser:
c = Contado
i = Iniciada
p = Pagado
a = Credito
n = nula
t = temporal';
COMMENT ON COLUMN FACTURAS.NOMBRE_TEMP IS 'Nombre utilizado de manera temporal de la factura, para indentificar el cliente.';
ALTER TABLE FACTURAS ADD CONSTRAINT FACTURAS_FK
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID);
ALTER TABLE FACTURAS ADD CONSTRAINT FK_FACTURA_2
  FOREIGN KEY (IDTURNO) REFERENCES TURNOS (ID);
COMMENT ON TABLE FACTURAS IS 'El campo estado puede ser  p=Pagado, c=credito, a=abono.';
ALTER TABLE GENERALES ADD CONSTRAINT FK_GENERALES_0
  FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS (ID);
ALTER TABLE GENERALES ADD CONSTRAINT FK_GENERALES_1
  FOREIGN KEY (ID_TIPO_SANGRE) REFERENCES TIPOS_SANGRE (ID);
COMMENT ON COLUMN GUIA_VIGILANCIA_DESARROLLO.ID IS 'Identificador para indentificar las caracteristicas del niño a su edad.';
COMMENT ON COLUMN GUIA_VIGILANCIA_DESARROLLO.EDAD IS 'Las edades que registran aqui son en meses';
COMMENT ON COLUMN GUIA_VIGILANCIA_DESARROLLO.CARACT_DESARR_EVALUAR IS 'Describe el comportamiento de niño a su edad.';
ALTER TABLE HUELLAS ADD CONSTRAINT HUELLAS_FK
  FOREIGN KEY (ID) REFERENCES PERSONAS (ID);
ALTER TABLE INSCRIPCION ADD CONSTRAINT FK_ESTUDIANTE
  FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE (ID);
ALTER TABLE INSCRIPCION ADD CONSTRAINT FK_PADRE_TUTOR
  FOREIGN KEY (ID_PADRE_TUTOR) REFERENCES PADRES (ID);
ALTER TABLE INSCRIPCION ADD CONSTRAINT FK_TANDAS
  FOREIGN KEY (ID_TANDA) REFERENCES TANDAS (ID);
ALTER TABLE MEDICAMENTOS ADD CONSTRAINT FK_MEDICAMENTOS_1
  FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES (ID);
ALTER TABLE MENSAJES ADD CONSTRAINT MENSAJES_FK
  FOREIGN KEY (ID_PACIENTE) REFERENCES PERSONAS (ID);
ALTER TABLE METRICAS ADD CONSTRAINT FK_METRICAS_1
  FOREIGN KEY (IDCONSULTA) REFERENCES CONSULTAS (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE MUNICIPIOS ADD CONSTRAINT IDPROVINCIA_IDX
  FOREIGN KEY (IDPROVINCIA) REFERENCES PROVINCIAS (ID);
ALTER TABLE PACIENTES ADD CONSTRAINT FK_PACIENTES_0
  FOREIGN KEY (ID) REFERENCES PERSONAS (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE PACIENTES ADD CONSTRAINT PACIENTES_FK
  FOREIGN KEY (ID_MADRE) REFERENCES PADRES (ID);
ALTER TABLE PACIENTES ADD CONSTRAINT PACIENTES_FK_1
  FOREIGN KEY (ID_PADRE) REFERENCES PADRES (ID);
ALTER TABLE PADRES ADD CONSTRAINT FK_PADRES_0
  FOREIGN KEY (ID) REFERENCES PERSONAS (ID);
COMMENT ON COLUMN PERSONAS.ID IS 'Identificador de la Persona en el sistema';
COMMENT ON COLUMN PERSONAS.PERSONA IS 'Identidad de una persona F Fisica o J Juridica.';
COMMENT ON COLUMN PERSONAS.APELLIDOS IS 'Apellidos Paternos + Maternos';
COMMENT ON COLUMN PERSONAS.SEXO IS 'El sexo solo se define como Masculino y Femenino';
COMMENT ON COLUMN PERSONAS.FECHA_NACIMIENTO IS 'Fecha de nacimiento, este campo debe ser actualizado por una persona autorizada.';
COMMENT ON COLUMN PERSONAS.FECHA_INGRESO IS 'Este campo nadie deberia de modificarlo.';
COMMENT ON COLUMN PERSONAS.FECHA_HORA_ULTIMO_UPDATE IS 'Este campo debe ser actualizado cada vez que el registro se actualice. ';
COMMENT ON COLUMN PERSONAS.ESTADO IS 'Este campo hace referencia a estado en el sistema de la persona, si es true activo o false inactivo.';
COMMENT ON COLUMN PERSONAS.IDUSUARIO IS 'Ident. del usuario que registro a la persona al sistema.';
COMMENT ON COLUMN PERSONAS.ROL_USUARIO IS 'Conocer el rol que tenia ese usuario cuando registro esta persona.';
CREATE INDEX IDX_PERSONAS1 ON PERSONAS (PNOMBRE);
CREATE INDEX IDX_PERSONAS2 ON PERSONAS (SNOMBRE);
CREATE INDEX IDX_PERSONAS3 ON PERSONAS (APELLIDOS);
CREATE INDEX IDX_PERSONAS4 ON PERSONAS (FECHA_NACIMIENTO);
CREATE INDEX IDX_PERSONAS5 ON PERSONAS (FECHA_INGRESO);
ALTER TABLE PRODUCTOS ADD CONSTRAINT FK_PRODUCTOS_0
  FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIAS (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE PROVEEDORES ADD CONSTRAINT FK_PROVEEDORES_0
  FOREIGN KEY (ID) REFERENCES PERSONAS (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
CREATE UNIQUE INDEX RECCOUNT_IDX1 ON RECCOUNT (TABLA);
ALTER TABLE RECETAS ADD CONSTRAINT FK_RECETAS_1
  FOREIGN KEY (IDCONSULTA) REFERENCES CONSULTAS (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE SINTOMAS ADD CONSTRAINT SINTOMAS_FK
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES (ID);