
CREATE PROCEDURE ADMIN_HABILITAR_TURNO (
    IDUSUARIO D_IDUSUARIO )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE PRO_PERMISOS (
    CONSULTAR D_BOOLEAN_F,
    INSERTAR D_BOOLEAN_F,
    ACTUALIZAR D_BOOLEAN_F,
    BORRAR D_BOOLEAN_F,
    REFERENCIA D_BOOLEAN_F,
    VISTA D_VARCHAR_45,
    LOGINUSER D_IDUSUARIO )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_DELETE_ARS (
    V_ID D_ID,
    ESTADO D_BOOLEAN_T )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_DELETE_CATEGORIAS (
    V_ID D_ID,
    ESTADO D_BOOLEAN_T )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_DELETE_CLIENTE_SB (
    V_ID D_ID,
    I_ESTADO D_BOOLEAN_T )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_DELETE_ESTUDIANTE (
    V_ID D_ID,
    I_ESTADO D_BOOLEAN_T )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_DELETE_PACIENTE (
    V_ID D_ID,
    I_ESTADO D_BOOLEAN_T )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_INSERT_ARS (
    DESCRIPCION D_VARCHAR_45,
    COVER_CONSULTA_POR_C D_DESCUENTO,
    ESTADO D_BOOLEAN_T )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_INSERT_CATEGORIAS (
    DESCRIPCION D_VARCHAR_25,
    IMAGEN_TEXTO D_BLOB_TEXTO,
    ESTADO D_BOOLEAN_T )
RETURNS (
    V_ID D_ID )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_INSERT_CLIENTE_SB (
    I_PERSONA D_PERSONA,
    I_CEDULA D_CEDULA,
    I_PNOMBRE D_NOMBRES,
    I_SNOMBRE D_NOMBRES,
    I_APELLIDOS D_APELLIDOS,
    I_SEXO D_SEXO,
    I_FECHA_NACIMIENTO D_FECHA,
    I_ESTADO D_BOOLEAN_T,
    I_ESTADO_CIVIL D_ESTADO_CIVIL )
RETURNS (
    V_ID D_ID )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_INSERT_DIRECCIONES (
    I_ID_PERSONA D_ID,
    I_ID_PROVINCIA D_ID,
    I_ID_MUNICIPIO D_ID,
    I_ID_DISTRITO_MUNICIPAL D_ID,
    I_ID_CODIGO_POSTAL D_ID,
    I_DIRECCION D_VARCHAR_255 )
RETURNS (
    O_ID D_ID )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_INSERT_DOCTOR (
    I_IDUSUARIO D_IDUSUARIO,
    I_CLAVE D_CLAVE,
    I_PNOMBRE D_NOMBRES,
    I_SNOMBRE D_NOMBRES,
    I_APELLIDOS D_APELLIDOS,
    I_ROL D_ROL,
    I_COD_EXEQUATUR D_VARCHAR_70,
    I_ESPECIALIDAD D_VARCHAR_70,
    I_ESTADO D_BOOLEAN_T,
    I_ADMINISTRADOR D_BOOLEAN_F )
RETURNS (
    O_SQL D_BLOB_TEXTO )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_INSERT_ENTRADA_PRODUCTOS (
    ID_PROVEEDOR D_ID,
    COD_FACTURA D_CODIGO,
    LINEA D_ID,
    ID_PRODUCTO D_ID,
    ENTRADA D_DINERO,
    FECHA_VECIMIENTO D_FECHA )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_INSERT_ESTUDIANTE (
    I_ID_ARS D_ID,
    I_NO_NSS D_VARCHAR_25,
    I_ID_TIPO_SANGRE D_ID,
    I_CEDULA D_CEDULA,
    I_PNOMBRE D_NOMBRES,
    I_SNOMBRE D_NOMBRES,
    I_APELLIDOS D_APELLIDOS,
    I_SEXO D_SEXO,
    I_FECHA_NACIMIENTO D_FECHA,
    I_ESTADO D_BOOLEAN_T,
    I_MATRICULA D_VARCHAR_15,
    I_ID_PADRE D_ID,
    I_ID_MADRE D_ID,
    I_ID_TUTOR D_ID,
    I_JCB_PARENTESCO D_ID )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_INSERT_PACIENTE (
    I_ID_PADRE D_ID,
    I_ID_MADRE D_ID,
    I_ID_ARS D_ID,
    I_NO_NSS D_VARCHAR_25,
    I_CEDULA D_CEDULA,
    I_PNOMBRE D_NOMBRES,
    I_SNOMBRE D_NOMBRES,
    I_APELLIDOS D_APELLIDOS,
    I_SEXO D_SEXO,
    I_FECHA_NACIMIENTO D_FECHA,
    I_ID_TIPO_SANGRE D_ID,
    I_ESTADO D_BOOLEAN_T )
RETURNS (
    V_ID D_ID )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_INSERT_PADRES (
    I_ID_PROVINCIA D_ID,
    I_ID_MUNICIPIO D_ID,
    I_ID_DISTRITO_MUNICIPAL D_ID,
    I_ID_CODIGOPOSTAL D_ID,
    I_ID_TIPO_SANGRE D_ID,
    I_CEDULA D_CEDULA,
    I_PNOMBRE D_NOMBRES,
    I_SNOMBRE D_NOMBRES,
    I_APELLIDOS D_APELLIDOS,
    I_SEXO D_SEXO,
    I_DIRECCION D_VARCHAR_70,
    I_FECHA_NACIMIENTO D_FECHA,
    I_ESTADO D_BOOLEAN_T,
    I_ESTADO_CIVIL D_ESTADO_CIVIL )
RETURNS (
    O_ID D_ID )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_INSERT_PROVEEDOR (
    I_ID_PROVINCIA D_ID,
    I_ID_MUNICIPIO D_ID,
    I_PERSONA D_PERSONA,
    I_CEDULA D_CEDULA,
    I_PNOMBRE D_NOMBRES,
    I_SNOMBRE D_NOMBRES,
    I_APELLIDOS D_APELLIDOS,
    I_SEXO D_SEXO,
    I_DIRECCION D_VARCHAR_255,
    I_ESTADO D_BOOLEAN_T,
    I_CODIGO_PROVEEDOR D_CODIGO )
RETURNS (
    V_ID D_ID )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_INSERT_USUARIOS (
    I_IDUSUARIO D_IDUSUARIO,
    I_CLAVE D_CLAVE,
    I_PNOMBRE D_NOMBRES,
    I_SNOMBRE D_NOMBRES,
    I_APELLIDOS D_APELLIDOS,
    I_ESTADO D_BOOLEAN_T,
    I_ADMINISTRADOR D_BOOLEAN_F,
    I_DESCRIPCION D_BLOB_TEXTO )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_RECCOUNT (
    TCOPERAC TYPE OF D_INSERT_DELETE,
    TCTABLAX TYPE OF D_VARCHAR_45 )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_RECCOUNT_ESTADO (
    TCOPERAC TYPE OF D_INSERT_DELETE,
    TCTABLAX TYPE OF D_VARCHAR_45,
    ESTADO TYPE OF D_BOOLEAN_F )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_SELECT_USUARIOS_TAGS (
    I_USER_NAME D_IDUSUARIO NOT NULL DEFAULT 'all' )
RETURNS (
    O_USER_NAME D_IDUSUARIO,
    O_PRIMER_NOMBRE D_NOMBRES,
    O_SEGUNDO_NOMBRE D_NOMBRES,
    O_APELLIDOS D_APELLIDOS,
    O_ESTADO_ACTIVO D_BOOLEAN_T,
    O_ADMINISTRADOR D_BOOLEAN_T,
    O_TAG_NOMBRE D_VARCHAR_255,
    O_TAG_VALOR D_VARCHAR_255 )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_UPDATE_CANTIDAD_FILAS (
    TNCODSUC D_ID )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_UPDATE_CLIENTE_SB (
    I_ID D_ID,
    I_PERSONA D_PERSONA,
    I_CEDULA D_CEDULA,
    I_PNOMBRE D_NOMBRES,
    I_SNOMBRE D_NOMBRES,
    I_APELLIDOS D_APELLIDOS,
    I_SEXO D_SEXO,
    I_FECHA_NACIMIENTO D_FECHA,
    I_ESTADO D_BOOLEAN_T,
    I_ESTADO_CIVIL D_ESTADO_CIVIL )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_UPDATE_DEUDA_ESTADO (
    E_ID_DEUDA D_ID NOT NULL,
    E_OBJ D_ESTADO_C_I_P_A_N_T NOT NULL )
RETURNS (
    S_SALIDA D_VARCHAR_15 )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_UPDATE_ESTUDIANTE (
    I_ID D_ID,
    I_ID_PADRE D_ID,
    I_ID_MADRE D_ID,
    I_ID_TUTOR D_ID,
    I_JCB_PARENTESCO D_ID,
    I_PNOMBRE D_NOMBRES,
    I_SNOMBRE D_NOMBRES,
    I_APELLIDOS D_APELLIDOS,
    I_SEXO D_SEXO,
    I_FECHA_NACIMIENTO D_FECHA,
    I_ESTADO D_BOOLEAN_T )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_UPDATE_PADRES (
    I_ID D_ID,
    I_ID_PROVINCIA D_ID,
    I_ID_MUNICIPIO D_ID,
    I_ID_DISTRITO_MUNICIPAL D_ID,
    I_ID_CODIGOPOSTAL D_ID,
    I_ID_TIPO_SANGRE D_ID,
    I_CEDULA D_CEDULA,
    I_PNOMBRE D_NOMBRES,
    I_SNOMBRE D_NOMBRES,
    I_APELLIDOS D_APELLIDOS,
    I_SEXO D_SEXO,
    I_DIRECCION D_VARCHAR_70,
    I_FECHA_NACIMIENTO D_FECHA,
    I_ESTADO D_BOOLEAN_T,
    I_ESTADO_CIVIL D_ESTADO_CIVIL )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SP_UPDATE_USUARIOS (
    I_IDUSUARIO D_IDUSUARIO,
    I_CLAVE D_CLAVE,
    I_PNOMBRE D_NOMBRES,
    I_SNOMBRE D_NOMBRES,
    I_APELLIDOS D_APELLIDOS,
    I_ESTADO D_BOOLEAN_T,
    I_ADMINISTRADOR D_BOOLEAN_F,
    I_DESCRIPCION D_BLOB_TEXTO )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SYSTEM_ENCRIPTAR (
    TCTEXTO D_BLOB_TEXTO,
    TCACCION CHAR(1),
    TCNUMEROENCRIPTACION D_VARCHAR_255,
    TCNUMEROREPETICION D_VARCHAR_255 )
RETURNS (
    FTCNUEVOTEXTO D_BLOB_TEXTO )

AS 
BEGIN SUSPEND; 
END;



CREATE PROCEDURE SYSTEM_SET_LICENCIA (
    E_FCHV CHAR(10),
    E_IDMAC VARCHAR(80),
    CLAVE1 CHAR(7),
    CLAVE2 CHAR(7) )

AS 
BEGIN SUSPEND; 
END;
